/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Image from "next/image";

function MobileContactItem({ icon, text }) {
  return (
    <div className="flex items-center mb-6">
      <Image src={icon} alt="" width={32} height={32} className="mr-4" />
      <span className="text-xl">{text}</span>
    </div>
  );
}

export default MobileContactItem;
