/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import Image from 'next/image';

const ContactItem = ({ src, alt, children }) => (
  <div className="flex flex-1 shrink gap-3 items-center py-2 basis-0 min-w-[240px]">
    <Image
      src={src}
      alt={alt}
      width={36}
      height={36}
      className="object-contain shrink-0 self-stretch my-auto w-9 aspect-square"
    />
    <div className="self-stretch my-auto min-w-[240px] w-[264px]">{children}</div>
  </div>
);

const ContactInfo = () => (
  <section className="flex overflow-hidden flex-col w-full font-semibold whitespace-nowrap max-md:max-w-full">
    <div className="flex gap-8 items-start py-8 pr-8 pl-16 w-full max-md:px-5 max-md:max-w-full max-sm:hidden">
      <div className="flex flex-wrap flex-1 shrink gap-8 items-start w-full basis-0 min-w-[240px] max-md:max-w-full">
        <div className="flex relative flex-1 shrink gap-3 items-start py-2 basis-0 min-w-[240px] text-neutral-400">
          <Image
            src="/images/email-icon.png"
            alt=""
            width={36}
            height={36}
            className="object-contain z-0 shrink-0 w-9 aspect-square"
          />
          <div className="absolute left-12 top-2/4 -translate-y-2/4 translate-x-[0%] w-[162px]">
            lsj.liu@mail.utoront.ca
          </div>
        </div>
        <ContactItem src="/images/phone-icon.png" alt="Phone icon">
          (514)-692-9575
        </ContactItem>
        <ContactItem src="/images/linkedin-icon.png" alt="LinkedIn icon">
          LinkedIn
        </ContactItem>
        <ContactItem src="/images/github-icon.png" alt="GitHub icon">
          GitHub
        </ContactItem>
      </div>
    </div>
  </section>
);

export default ContactInfo;