/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import NavBar from './NavBar';
import ContactInfo from './ContactInfo';
import PersonalJourney from './PersonalJourney';
import AboutMe from './AboutMe/AboutMe';
import ContactSection from './ContactSection/ContactSection';
const Layout = ({ children }) => (
  <div className="flex overflow-hidden flex-col text-base bg-black text-neutral-400">
    <NavBar />
    <main>{children}</main>
    <PersonalJourney/>
    <AboutMe/>
    <ContactSection/>
  </div>
);

export default Layout;