/**
 * This code was generated by Builder.io.
 */
import React from "react";

function AboutMeHeader() {
  return (
    <h1 className="overflow-hidden flex-1 shrink text-4xl font-bold leading-tight min-w-[240px] max-md:max-w-full">
      About Me
    </h1>
  );
}

export default AboutMeHeader;
